import 'package:g_gizmo/Pages/home.dart';

class MyProducts{
  static List<Product> allProducts=[
    Product(id: 1,
        name: 'Stand Up Chair',
        category: 'Trending Now!',
        image: 'assets/images/products/Wooden Photo Chair.jpeg',
        description: 'Clean Wooden Photo Chair from a High Powered Makers' ,
        price: 400,
        quantity: 1,),
    Product(id: 1,
        name: "Frame",
        category: "In Stock",
        image: "assets/images/products/Flower Frame.jpeg",
        description: "Best Quality Frame you can find with the perfect pixels edge.",
        price: 500,
        quantity: 1, ),
    Product(id: 1,
        name: 'Sofa',
        category: 'Out Of Stock!',
        image: 'assets/images/products/Yellow sofa.jpeg',
        description: 'Clean sounds for your eardrums from a High Powered AirPod 1 pro' ,
        price: 2000,
        quantity: 1, ),
    Product(id: 1,
        name: "Speaker",
        category: "In Stock",
        image: "assets/images/products/Earpods 1.jpeg",
        description: "Best Quality Frame you can find with the perfect pixels edge.",
        price: 500,
        quantity: 1, ),
    Product(id: 1,
        name: 'Black HeadPhones Max',
        category: 'Trending Now!',
        image: 'assets/images/products/Play Station.jpeg',
        description: 'Clean sounds for your eardrums from a High Powered AirPod 1 pro' ,
        price: 250,
        quantity: 1, ),
    Product(id: 1,
        name: "Earpods",
        category: "In Stock",
        image: "assets/images/products/Dryer.jpeg",
        description: "Best Quality Frame you can find with the perfect pixels edge.",
        price: 300,
        quantity: 1, ),
  ];
  static List<Product> games=[
    Product(id: 1,
        name: 'Play Station 2',
        category: 'Trending Now!',
        image: 'assets/images/products/Play Station 2.jpeg',
        description: ' Best Console Games in Town Now' ,
        price: 400,
        quantity: 1, ),
    Product(id: 1,
        name: "Play Station 5",
        category: "In Stock",
        image: "assets/images/products/Ps3.jpeg",
        description: "PS5 with High End Games.",
        price: 600,
        quantity: 1, ),
    Product(id: 1,
        name: 'Play Station ',
        category: 'Trending Now!',
        image: 'assets/images/products/Speaker.jpeg',
        description: ' Best Console Games in Town Now' ,
        price: 300,
        quantity: 1,),
    Product(id: 1,
        name: "Play Station 5",
        category: "In Stock",
        image: "assets/images/products/Earpod Pro.jpeg",
        description: "PS5 with High End Games.",
        price: 800,
        quantity: 1,),
    Product(id: 1,
        name: 'Head Phones Pro',
        category: 'Trending Now!',
        image: 'assets/images/products/Smart Tv.jpeg',
        description: ' Best Console Games in Town Now' ,
        price: 250,
        quantity: 1, ),
    Product(id: 1,
        name: "Smart Tv",
        category: "In Stock",
        image: "assets/images/products/Camera.jpeg",
        description: "PS5 with High End Games.",
        price: 2000,
        quantity: 1,),
  ];
  static List<Product> applainces=[
    Product(id: 1,
        name: 'Iron',
        category: 'In Stock',
        image: 'assets/images/products/Normal Iron.jpeg',
        description: 'High Quality Iron With The Best Degree Of Hotness' ,
        price: 250,
        quantity: 1, ),
    Product(id: 1,
        name: "Camera",
        category: "In Stock",
        image: "assets/images/products/Camera1.jpeg",
        description: "Best Quality Camera you can find avaliablbe with HD Quad Lens.",
        price: 600,
        quantity: 1, ),
    Product(id: 1,
        name: 'Washing Machine',
        category: 'In Stock',
        image: 'assets/images/products/Washing Machine.jpeg',
        description: 'High Quality Iron With The Best Degree Of Hotness' ,
        price: 700,
        quantity: 1, ),
    Product(id: 1,
        name: "Blender",
        category: "In Stock",
        image: "assets/images/products/Blender Full Set.jpeg",
        description: "Best Quality Camera you can find avaliablbe with HD Quad Lens.",
        price: 600,
        quantity: 1, ),
    Product(id: 1,
        name: 'Coffee Maker',
        category: 'In Stock',
        image: 'assets/images/products/normal iron (2).jpeg',
        description: 'High Quality Iron With The Best Degree Of Hotness' ,
        price: 250,
        quantity: 1,),
    Product(id: 1,
        name: "Whissker",
        category: "In Stock",
        image: "assets/images/products/Black Headphone.jpeg",
        description: "Best Quality Camera you can find avaliablbe with HD Quad Lens.",
        price: 150,
        quantity: 1, ),
  ];

}